/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Merchant Crypto Wallet Dashboard API
 * MVP API contract for merchant crypto wallet dashboard
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiKeyResponse,
  ApiKeysResponse,
  AuthResponse,
  CreateModuleRequest,
  GetOrgsOrgIdTransactionsParams,
  MeResponse,
  Module,
  MoneyBalance,
  PostAuthOtpSendBody,
  PostAuthOtpVerifyBody,
  Storefront,
  TransactionsResponse,
  UpdateModuleRequest,
} from "./generated/schemas";

import { customInstance } from "./fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Send OTP to email
 */
export const postAuthOtpSend = (
  postAuthOtpSendBody: PostAuthOtpSendBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<void>(
    {
      url: `/auth/otp/send`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthOtpSendBody,
      signal,
    },
    options
  );
};

export const getPostAuthOtpSendMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOtpSend>>,
    TError,
    { data: PostAuthOtpSendBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOtpSend>>,
  TError,
  { data: PostAuthOtpSendBody },
  TContext
> => {
  const mutationKey = ["postAuthOtpSend"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOtpSend>>,
    { data: PostAuthOtpSendBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOtpSend(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOtpSendMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOtpSend>>
>;
export type PostAuthOtpSendMutationBody = PostAuthOtpSendBody;
export type PostAuthOtpSendMutationError = unknown;

/**
 * @summary Send OTP to email
 */
export const usePostAuthOtpSend = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOtpSend>>,
      TError,
      { data: PostAuthOtpSendBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOtpSend>>,
  TError,
  { data: PostAuthOtpSendBody },
  TContext
> => {
  const mutationOptions = getPostAuthOtpSendMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Verify OTP and authenticate
 */
export const postAuthOtpVerify = (
  postAuthOtpVerifyBody: PostAuthOtpVerifyBody,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<AuthResponse>(
    {
      url: `/auth/otp/verify`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthOtpVerifyBody,
      signal,
    },
    options
  );
};

export const getPostAuthOtpVerifyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOtpVerify>>,
    TError,
    { data: PostAuthOtpVerifyBody },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOtpVerify>>,
  TError,
  { data: PostAuthOtpVerifyBody },
  TContext
> => {
  const mutationKey = ["postAuthOtpVerify"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOtpVerify>>,
    { data: PostAuthOtpVerifyBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOtpVerify(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOtpVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOtpVerify>>
>;
export type PostAuthOtpVerifyMutationBody = PostAuthOtpVerifyBody;
export type PostAuthOtpVerifyMutationError = unknown;

/**
 * @summary Verify OTP and authenticate
 */
export const usePostAuthOtpVerify = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOtpVerify>>,
      TError,
      { data: PostAuthOtpVerifyBody },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOtpVerify>>,
  TError,
  { data: PostAuthOtpVerifyBody },
  TContext
> => {
  const mutationOptions = getPostAuthOtpVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Get current user and org
 */
export const getMe = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<MeResponse>(
    { url: `/me`, method: "GET", signal },
    options
  );
};

export const getGetMeQueryKey = () => {
  return [`/me`] as const;
};

export const getGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({
    signal,
  }) => getMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>;
export type GetMeQueryError = unknown;

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user and org
 */

export function useGetMe<
  TData = Awaited<ReturnType<typeof getMe>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary List storefronts for org
 */
export const getOrgsOrgIdStorefronts = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Storefront[]>(
    { url: `/orgs/${orgId}/storefronts`, method: "GET", signal },
    options
  );
};

export const getGetOrgsOrgIdStorefrontsQueryKey = (orgId?: string) => {
  return [`/orgs/${orgId}/storefronts`] as const;
};

export const getGetOrgsOrgIdStorefrontsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOrgsOrgIdStorefrontsQueryKey(orgId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>
  > = ({ signal }) => getOrgsOrgIdStorefronts(orgId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orgId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrgsOrgIdStorefrontsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>
>;
export type GetOrgsOrgIdStorefrontsQueryError = unknown;

export function useGetOrgsOrgIdStorefronts<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
  TError = unknown,
>(
  orgId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdStorefronts<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdStorefronts<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List storefronts for org
 */

export function useGetOrgsOrgIdStorefronts<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefronts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOrgsOrgIdStorefrontsQueryOptions(orgId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get balance for storefront
 */
export const getOrgsOrgIdStorefrontsSfIdBalance = (
  orgId: string,
  sfId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<MoneyBalance>(
    {
      url: `/orgs/${orgId}/storefronts/${sfId}/balance`,
      method: "GET",
      signal,
    },
    options
  );
};

export const getGetOrgsOrgIdStorefrontsSfIdBalanceQueryKey = (
  orgId?: string,
  sfId?: string
) => {
  return [`/orgs/${orgId}/storefronts/${sfId}/balance`] as const;
};

export const getGetOrgsOrgIdStorefrontsSfIdBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
  TError = unknown,
>(
  orgId: string,
  sfId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetOrgsOrgIdStorefrontsSfIdBalanceQueryKey(orgId, sfId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>
  > = ({ signal }) =>
    getOrgsOrgIdStorefrontsSfIdBalance(orgId, sfId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(orgId && sfId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrgsOrgIdStorefrontsSfIdBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>
>;
export type GetOrgsOrgIdStorefrontsSfIdBalanceQueryError = unknown;

export function useGetOrgsOrgIdStorefrontsSfIdBalance<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
  TError = unknown,
>(
  orgId: string,
  sfId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdStorefrontsSfIdBalance<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
  TError = unknown,
>(
  orgId: string,
  sfId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdStorefrontsSfIdBalance<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
  TError = unknown,
>(
  orgId: string,
  sfId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get balance for storefront
 */

export function useGetOrgsOrgIdStorefrontsSfIdBalance<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
  TError = unknown,
>(
  orgId: string,
  sfId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdStorefrontsSfIdBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOrgsOrgIdStorefrontsSfIdBalanceQueryOptions(
    orgId,
    sfId,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary List transactions with pagination
 */
export const getOrgsOrgIdTransactions = (
  orgId: string,
  params?: GetOrgsOrgIdTransactionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<TransactionsResponse>(
    { url: `/orgs/${orgId}/transactions`, method: "GET", params, signal },
    options
  );
};

export const getGetOrgsOrgIdTransactionsQueryKey = (
  orgId?: string,
  params?: GetOrgsOrgIdTransactionsParams
) => {
  return [`/orgs/${orgId}/transactions`, ...(params ? [params] : [])] as const;
};

export const getGetOrgsOrgIdTransactionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetOrgsOrgIdTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetOrgsOrgIdTransactionsQueryKey(orgId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>
  > = ({ signal }) =>
    getOrgsOrgIdTransactions(orgId, params, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orgId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrgsOrgIdTransactionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>
>;
export type GetOrgsOrgIdTransactionsQueryError = unknown;

export function useGetOrgsOrgIdTransactions<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
  TError = unknown,
>(
  orgId: string,
  params: undefined | GetOrgsOrgIdTransactionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdTransactions<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetOrgsOrgIdTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdTransactions<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetOrgsOrgIdTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List transactions with pagination
 */

export function useGetOrgsOrgIdTransactions<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetOrgsOrgIdTransactionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdTransactions>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOrgsOrgIdTransactionsQueryOptions(
    orgId,
    params,
    options
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary List modules for org
 */
export const getOrgsOrgIdModules = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Module[]>(
    { url: `/orgs/${orgId}/modules`, method: "GET", signal },
    options
  );
};

export const getGetOrgsOrgIdModulesQueryKey = (orgId?: string) => {
  return [`/orgs/${orgId}/modules`] as const;
};

export const getGetOrgsOrgIdModulesQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOrgsOrgIdModulesQueryKey(orgId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOrgsOrgIdModules>>
  > = ({ signal }) => getOrgsOrgIdModules(orgId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orgId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrgsOrgIdModulesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrgsOrgIdModules>>
>;
export type GetOrgsOrgIdModulesQueryError = unknown;

export function useGetOrgsOrgIdModules<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
  TError = unknown,
>(
  orgId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdModules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdModules<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdModules>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdModules<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List modules for org
 */

export function useGetOrgsOrgIdModules<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdModules>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOrgsOrgIdModulesQueryOptions(orgId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new module
 */
export const postOrgsOrgIdModules = (
  orgId: string,
  createModuleRequest: CreateModuleRequest,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<Module>(
    {
      url: `/orgs/${orgId}/modules`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createModuleRequest,
      signal,
    },
    options
  );
};

export const getPostOrgsOrgIdModulesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOrgsOrgIdModules>>,
    TError,
    { orgId: string; data: CreateModuleRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOrgsOrgIdModules>>,
  TError,
  { orgId: string; data: CreateModuleRequest },
  TContext
> => {
  const mutationKey = ["postOrgsOrgIdModules"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOrgsOrgIdModules>>,
    { orgId: string; data: CreateModuleRequest }
  > = (props) => {
    const { orgId, data } = props ?? {};

    return postOrgsOrgIdModules(orgId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOrgsOrgIdModulesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOrgsOrgIdModules>>
>;
export type PostOrgsOrgIdModulesMutationBody = CreateModuleRequest;
export type PostOrgsOrgIdModulesMutationError = unknown;

/**
 * @summary Create a new module
 */
export const usePostOrgsOrgIdModules = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOrgsOrgIdModules>>,
      TError,
      { orgId: string; data: CreateModuleRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postOrgsOrgIdModules>>,
  TError,
  { orgId: string; data: CreateModuleRequest },
  TContext
> => {
  const mutationOptions = getPostOrgsOrgIdModulesMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary Update a module
 */
export const patchOrgsOrgIdModulesModuleId = (
  orgId: string,
  moduleId: string,
  updateModuleRequest: UpdateModuleRequest,
  options?: SecondParameter<typeof customInstance>
) => {
  return customInstance<Module>(
    {
      url: `/orgs/${orgId}/modules/${moduleId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateModuleRequest,
    },
    options
  );
};

export const getPatchOrgsOrgIdModulesModuleIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchOrgsOrgIdModulesModuleId>>,
    TError,
    { orgId: string; moduleId: string; data: UpdateModuleRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchOrgsOrgIdModulesModuleId>>,
  TError,
  { orgId: string; moduleId: string; data: UpdateModuleRequest },
  TContext
> => {
  const mutationKey = ["patchOrgsOrgIdModulesModuleId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchOrgsOrgIdModulesModuleId>>,
    { orgId: string; moduleId: string; data: UpdateModuleRequest }
  > = (props) => {
    const { orgId, moduleId, data } = props ?? {};

    return patchOrgsOrgIdModulesModuleId(orgId, moduleId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchOrgsOrgIdModulesModuleIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchOrgsOrgIdModulesModuleId>>
>;
export type PatchOrgsOrgIdModulesModuleIdMutationBody = UpdateModuleRequest;
export type PatchOrgsOrgIdModulesModuleIdMutationError = unknown;

/**
 * @summary Update a module
 */
export const usePatchOrgsOrgIdModulesModuleId = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchOrgsOrgIdModulesModuleId>>,
      TError,
      { orgId: string; moduleId: string; data: UpdateModuleRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patchOrgsOrgIdModulesModuleId>>,
  TError,
  { orgId: string; moduleId: string; data: UpdateModuleRequest },
  TContext
> => {
  const mutationOptions =
    getPatchOrgsOrgIdModulesModuleIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

/**
 * @summary List API keys for org
 */
export const getOrgsOrgIdApikeys = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ApiKeysResponse>(
    { url: `/orgs/${orgId}/apikeys`, method: "GET", signal },
    options
  );
};

export const getGetOrgsOrgIdApikeysQueryKey = (orgId?: string) => {
  return [`/orgs/${orgId}/apikeys`] as const;
};

export const getGetOrgsOrgIdApikeysQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOrgsOrgIdApikeysQueryKey(orgId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>
  > = ({ signal }) => getOrgsOrgIdApikeys(orgId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orgId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrgsOrgIdApikeysQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>
>;
export type GetOrgsOrgIdApikeysQueryError = unknown;

export function useGetOrgsOrgIdApikeys<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
  TError = unknown,
>(
  orgId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdApikeys<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
          TError,
          Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetOrgsOrgIdApikeys<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List API keys for org
 */

export function useGetOrgsOrgIdApikeys<
  TData = Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
  TError = unknown,
>(
  orgId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getOrgsOrgIdApikeys>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetOrgsOrgIdApikeysQueryOptions(orgId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Create a new API key
 */
export const postOrgsOrgIdApikeys = (
  orgId: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal
) => {
  return customInstance<ApiKeyResponse>(
    { url: `/orgs/${orgId}/apikeys`, method: "POST", signal },
    options
  );
};

export const getPostOrgsOrgIdApikeysMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOrgsOrgIdApikeys>>,
    TError,
    { orgId: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOrgsOrgIdApikeys>>,
  TError,
  { orgId: string },
  TContext
> => {
  const mutationKey = ["postOrgsOrgIdApikeys"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOrgsOrgIdApikeys>>,
    { orgId: string }
  > = (props) => {
    const { orgId } = props ?? {};

    return postOrgsOrgIdApikeys(orgId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOrgsOrgIdApikeysMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOrgsOrgIdApikeys>>
>;

export type PostOrgsOrgIdApikeysMutationError = unknown;

/**
 * @summary Create a new API key
 */
export const usePostOrgsOrgIdApikeys = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOrgsOrgIdApikeys>>,
      TError,
      { orgId: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof postOrgsOrgIdApikeys>>,
  TError,
  { orgId: string },
  TContext
> => {
  const mutationOptions = getPostOrgsOrgIdApikeysMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
